### ISSUE TITLE
"Duplicate Column" error in Downcode Variable creation

### ISSUE THREAD

**Issue by Viqsi** [MathematicalMedicine/diver-issues#152]
This occurred during VV's demo to NIH, on diver.mathmed.org. Here's the complete log of what we got from diverRPC:

```
[2023-05-08 14:37:23,405] DEBUG in diverRPC: ----------------------------------------------------
[2023-05-08 14:37:23,406] DEBUG in diverRPC: Args: None | Body: {'construct_type': 'downcode',
 'defaultValue': '2',
 'description': 'affective vs nonaffective',
 'name': 'demo_temp',
 'projectid': 33,
 'values': [{'definition': {'constraints': [{'constraint_type': 'EQ',
                                             'constraint_value': 'Bipolar '
                                                                 'Disorder, '
                                                                 'Type II',
                                             'order': 2,
                                             'variable_name': 'dist_dx_nimh'}],
                            'relationship': 'OR'},
             'description': 'nonaffective',
             'name': '0'},
            {'definition': {'constraints': [{'constraint_type': 'EQ',
                                             'constraint_value': 'Major '
                                                                 'Depressive '
                                                                 'Disorder',
                                             'order': 0,
                                             'variable_name': 'dist_dx_nimh'},
                                            {'constraint_type': 'EQ',
                                             'constraint_value': 'Bipolar '
                                                                 'Disorder, '
                                                                 'Type I',
                                             'order': 1,
                                             'variable_name': 'dist_dx_nimh'}],
                            'relationship': 'OR'},
             'description': 'affective',
             'name': '1'},
            {'definition': {'constraints': [], 'relationship': 'OR'},
             'description': '',
             'name': 'unk'}],
 'variable_limit': 1,
 'variables': ['dist_dx_nimh']}
[2023-05-08 14:37:31,614] DEBUG in diverAPI: proc API_CreateConstructVariable called, args ('testuser', 33, 'demo_temp', 'downcode', 'affective vs nonaffective', '{"name": "demo_temp", "description": "affective vs nonaffective", "construct_type": "downcode", "values": [{"definition": {"relationship": "OR", "constraints": [{"variable_name": "dist_dx_nimh", "constraint_type": "EQ", "constraint_value": "Bipolar Disorder, Type II", "order": 2}]}, "name": "0", "description": "nonaffective"}, {"definition": {"relationship": "OR", "constraints": [{"variable_name": "dist_dx_nimh", "constraint_type": "EQ", "constraint_value": "Major Depressive Disorder", "order": 0}, {"variable_name": "dist_dx_nimh", "constraint_type": "EQ", "constraint_value": "Bipolar Disorder, Type I", "order": 1}]}, "name": "1", "description": "affective"}, {"definition": {"relationship": "OR", "constraints": []}, "name": "unk", "description": ""}], "defaultValue": "2", "variable_limit": 1, "variables": ["dist_dx_nimh"]}'), result (first 1000 chars only): [{'cohort_rows': 122107, 'new_cohort_id': 777}]
[2023-05-08 14:37:31,630] DEBUG in diverAPI: procresult: [{'new_cohort_id': 778, 'cohort_rows': 0}]
[2023-05-08 14:37:35,929] DEBUG in diverAPI: procresult: [{'id': 97}]
127.0.0.1 - - [08/May/2023 14:37:44] "POST /api/v0/construct/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/lib/diver/diverRPC/diverRPC.py", line 698, in route_new_construct
    return flask.jsonify(diverAPI.new_construct(user, projectid, name,
  File "/var/lib/diver/diverRPC/diverAPI.py", line 675, in new_construct
    procresult = proccall_nextset(cursor)
  File "/var/lib/diver/diverRPC/diverAPI.py", line 155, in proccall_nextset
    if cursor.nextset():
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/cursors.py", line 96, in nextset
    return self._nextset(False)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/cursors.py", line 91, in _nextset
    conn.next_result(unbuffered=unbuffered)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/connections.py", line 552, in next_result
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/var/lib/diver/mambaforge/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1060, "Duplicate column name 'dist_dx_nimh'")
[2023-05-08 14:38:19,657] DEBUG in diverRPC: ----------------------------------------------------
```
...and from the `Diag` table in the database:
```
MariaDB [DIVER]> SELECT * FROM Diag WHERE InsertTime BETWEEN '2023-05-08 14:37:00' AND '2023-05-08 14:38:00'\G
*************************** 1. row ***************************
      DiagId: 23897
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:23
     Message: API_BuildALLEXISTSCohort entry with inUserName [testuser], inProjectId [33], inVariableName [demo_temp], inBaseCohortId [1], inRecursiveDepth [0] inVariableOrdinal [0]
*************************** 2. row ***************************
      DiagId: 23898
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:23
     Message: Recreating (without TRUNCATE or DELETE for now) TEMP_AECIds for demo_temp
*************************** 3. row ***************************
      DiagId: 23899
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:23
     Message: Looking for AECId for owner testuser, projectId 33 and name demo_temp_ALL_EXISTS
*************************** 4. row ***************************
      DiagId: 23900
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:23
     Message: Construct demo_temp is NOT instantiated, creating new AEC cohort from ["dist_dx_nimh"]
*************************** 5. row ***************************
      DiagId: 23901
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:23
     Message: API_BuildALLEXISTSCohort entry with inUserName [testuser], inProjectId [33], inVariableName [dist_dx_nimh], inBaseCohortId [1], inRecursiveDepth [1] inVariableOrdinal [0]
*************************** 6. row ***************************
      DiagId: 23902
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:23
     Message: Looking for AECId for owner testuser, projectId 33 and name dist_dx_nimh_ALL_EXISTS
*************************** 7. row ***************************
      DiagId: 23903
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:23
     Message: Creating new all-EXISTS cohort for dist_dx_nimh
*************************** 8. row ***************************
      DiagId: 23904
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: API_BuildALLEXISTSCohort exit, outAECId [777]
*************************** 9. row ***************************
      DiagId: 23905
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: AECId for dist_dx_nimh came back as 777
*************************** 10. row ***************************
      DiagId: 23906
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: Adding dist_dx_nimh w/AECId 777 for demo_temp
*************************** 11. row ***************************
      DiagId: 23907
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: demo_temp, dist_dx_nimh, 777
*************************** 12. row ***************************
      DiagId: 23908
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: demo_temp, dist_dx_nimh, 777
*************************** 13. row ***************************
      DiagId: 23909
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: demo_temp, dist_dx_nimh, 777
*************************** 14. row ***************************
      DiagId: 23910
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: demo_temp, dist_dx_nimh, 777
*************************** 15. row ***************************
      DiagId: 23914
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: API_BuildALLEXISTSCohort entry with inUserName [testuser], inProjectId [33], inVariableName [demo_temp], inBaseCohortId [1], inRecursiveDepth [0] inVariableOrdinal [0]
*************************** 16. row ***************************
      DiagId: 23915
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: Recreating (without TRUNCATE or DELETE for now) TEMP_AECIds for demo_temp
*************************** 17. row ***************************
      DiagId: 23916
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: Looking for AECId for owner testuser, projectId 33 and name demo_temp_ALL_EXISTS
*************************** 18. row ***************************
      DiagId: 23917
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:31
     Message: NULL
*************************** 19. row ***************************
      DiagId: 23918
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:35
     Message: Created initial new construct AEC with AECId of 778
*************************** 20. row ***************************
      DiagId: 23919
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:35
     Message: "Envalue" our "unvalued" construct AEC using operations on the union of component AECs
*************************** 21. row ***************************
      DiagId: 23920
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:36
     Message: Dynamic SQL is UPDATE IGNORE TEMP_VALUES a, cohortInds b SET a.dist_dx_nimh = b.value WHERE b.cohortId = 770 AND a.ind_id = b.ind_id;
*************************** 22. row ***************************
      DiagId: 23921
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:40
     Message: Dynamic SQL is UPDATE IGNORE TEMP_VALUES a, cohortInds b SET a.tempdxfinal = b.value WHERE b.cohortId = 771 AND a.ind_id = b.ind_id;
*************************** 23. row ***************************
      DiagId: 23922
ConnectionId: NULL
  InsertTime: 2023-05-08 14:37:43
     Message: Dynamic SQL is UPDATE IGNORE TEMP_VALUES a, cohortInds b SET a.I790 = b.value WHERE b.cohortId = 773 AND a.ind_id = b.ind_id;
23 rows in set (0.032 sec)
```

The variable appeared to show up in queries afterwards, but whether or not it's actually functional is unknown.

I was trying to unofficially investigate this one, but haven't been able to pin it down. The closest I got to figuring out something going wrong was that, when trying to reproduce it locally, I got subtly different results:

```
[2023-05-17 15:11:33,400] DEBUG in diverRPC: ----------------------------------------------------
[2023-05-17 15:11:33,401] DEBUG in diverRPC: Args: None | Body: {'construct_type': 'downcode',
 'defaultValue': '2',
 'description': 'affective vs nonaffective (local remake attempt)',
 'name': 'demo_temp',
 'projectid': 13,
 'values': [{'definition': {'constraints': [{'constraint_type': 'EQ',
                                             'constraint_value': 'Bipolar '
                                                                 'Disorder, '
                                                                 'Type II',
                                             'order': 0,
                                             'variable_name': 'dist_dx_nimh'}],
                            'relationship': 'OR'},
             'description': 'nonaffective',
             'name': '0'},
            {'definition': {'constraints': [{'constraint_type': 'EQ',
                                             'constraint_value': 'Major '
                                                                 'Depressive '
                                                                 'Disorder',
                                             'order': 1,
                                             'variable_name': 'dist_dx_nimh'},
                                            {'constraint_type': 'EQ',
                                             'constraint_value': 'Bipolar '
                                                                 'Disorder, '
                                                                 'Type I',
                                             'order': 2,
                                             'variable_name': 'dist_dx_nimh'}],
                            'relationship': 'OR'},
             'description': 'affective',
             'name': '1'},
            {'definition': {'constraints': [], 'relationship': 'OR'},
             'description': '',
             'name': 'unk'}],
 'variable_limit': 1,
 'variables': ['dist_dx_nimh']}
[2023-05-17 15:11:40,996] DEBUG in diverAPI: proc API_CreateConstructVariable called, args ('testuser', 13, 'demo_temp', 'downcode', 'affective vs nonaffective (local remake attempt)', '{"name": "demo_temp", "description": "affective vs nonaffective (local remake attempt)", "construct_type": "downcode", "values": [{"definition": {"relationship": "OR", "constraints": [{"variable_name": "dist_dx_nimh", "constraint_type": "EQ", "constraint_value": "Bipolar Disorder, Type II", "order": 0}]}, "name": "0", "description": "nonaffective"}, {"definition": {"relationship": "OR", "constraints": [{"variable_name": "dist_dx_nimh", "constraint_type": "EQ", "constraint_value": "Major Depressive Disorder", "order": 1}, {"variable_name": "dist_dx_nimh", "constraint_type": "EQ", "constraint_value": "Bipolar Disorder, Type I", "order": 2}]}, "name": "1", "description": "affective"}, {"definition": {"relationship": "OR", "constraints": []}, "name": "unk", "description": ""}], "defaultValue": "2", "variable_limit": 1, "variables": ["dist_dx_nimh"]}'), result (first 1000 chars only): [{'cohort_rows': 122107, 'new_cohort_id': 717}]
[2023-05-17 15:11:41,014] DEBUG in diverAPI: procresult: [{'new_cohort_id': 718, 'cohort_rows': 0}]
[2023-05-17 15:11:42,405] DEBUG in diverAPI: procresult: [{'id': 87}]
[2023-05-17 15:11:48,295] DEBUG in diverAPI: procresult: [{'id': 208, 'AECId': 718}]
[2023-05-17 15:11:48,296] DEBUG in diverAPI: procresult: ()
127.0.0.1 - - [17/May/2023 15:11:48] "POST /api/v0/construct/new HTTP/1.1" 200 -
[2023-05-17 15:11:48,365] DEBUG in diverRPC: ----------------------------------------------------
```
(I don't have `Diag` messages for this attempt because I don't know how to turn that facility on.)

In my case the variable was created just fine without any error.

The big noticable difference is that I got two more "proceresult" lines - one with an AECId field, and then one that was empty.

It evidently blew up in the middle of API_BuildALLEXISTSCohort, but beyond that I'm not sure where, and I don't know that proc well enough to pin it down. My suspicion is that it *mostly* created the variable but then blew up trying to set up values for it or something.

**Comment by Viqsi** [comment]
Incidentally, I hadn't noticed this in the tracker earlier because I thought it was related to some issue with the state of the d.m.o database and thus possibly Not A Bug (or a different kind of bug). But I can't figure it out well enough to determine if that's actually the issue or not.

Stuff like this is part of what motivated #149, incidentally...

**Comment by WValenti** [comment]
The only way I can imagine there being a duplicate column created is in the temporary table being used to determine values for the new variable if there was a failure to clean-up after a problem in an earlier operation. I have not been able to reproduce this. I can make the creation atomic as mentioned earlier, but I hesitate to "eliminate" bugs that I cannot reproduce as I then cannot prove that the fix worked.  I will continue to poke around.

**Comment by Viqsi** [comment]
I encountered this again when setting up for the demo on the 10th:

```
[2023-08-10 01:51:26,214] DEBUG in diverAPI: proc API_CreateConstructVariable called, args ('jvc', 18, 'HeardStuffYN', 'downcode', '', '{"name": "HeardStuffYN", "description": "", "construct_type": "downcode", "values": [{"definition": {"relationship": "OR", "constraints": [{"variable_name": "I10920", "constraint_type": "EQ", "constraint_value": "1", "order": 0}, {"variable_name": "I10920", "constraint_type": "EQ", "constraint_value": "2", "order": 1}]}, "name": "Yes", "description": ""}, {"definition": {"relationship": "OR", "constraints": []}, "name": "No", "description": ""}], "defaultValue": "1", "variable_limit": 1, "variables": ["I10920"]}'), result (first 1000 chars only): [{'cohort_rows': 0, 'new_cohort_id': 683}]
[2023-08-10 01:51:26,424] DEBUG in diverAPI: procresult: [{'id': 82}]
127.0.0.1 - - [10/Aug/2023 01:51:27] "POST /api/v0/construct/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jvc/diverRPC/diverRPC.py", line 746, in route_new_construct
    return flask.jsonify(diverAPI.new_construct(user, projectid, name,
  File "/home/jvc/diverRPC/diverAPI.py", line 717, in new_construct
    procresult = proccall_nextset(cursor)
  File "/home/jvc/diverRPC/diverAPI.py", line 168, in proccall_nextset
    if cursor.nextset():
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/cursors.py", line 96, in nextset
    return self._nextset(False)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/cursors.py", line 91, in _nextset
    conn.next_result(unbuffered=unbuffered)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/connections.py", line 552, in next_result
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1060, "Duplicate column name 'I10920'")
```


The custom variable gets created anyways. I suspect what's going on is that I was creating a custom variable that was virtualy identical to one I'd already made in a different project (the only difference being that I'd changed the name, because #158 had already bitten me).

**Comment by Viqsi** [comment]
This apears to happen as a result of the `TEMP_VALUES` table that's manipulated as part of "envaluing" already existing with the column in question. My guesses:
* This could be a symptom of a failed prior attempt to create the construct.
* The process could be choking on a given variable being accidentally listed twice as part of determining what variables the construct relies on (it's in the equivalent of a `foreach` loop for each component variable of the construct).

I'm not sure which it is (or if it's something else entirely), but that torch has been passed to @WValenti and I may also brain it here and there. Per a Skype conversation he'd be looking at making `TEMP_VALUES` a legitimately temporary table.

**Comment by Viqsi** [comment]
Found a consistent way to reproduce it.
* Create a custom variable via downcoding.
* Create a combined custom variable, combining that downcoded variable with another variable.
* Delete these two custom variables.
* Recreate the downcode custom variable, making sure to use the same name of the variable just deleted.
* Attempt to recreate the combined custom variable.

It appears to be another side effect of #217. We're testing a workaround right now (which would also fix that bug, if it's stable).
