### ISSUE TITLE
Variable Set names currently required to be unique across user projects

### ISSUE THREAD

**Issue by Viqsi** [MathematicalMedicine/diver-issues#158]
```
Traceback (most recent call last):
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/jvc/diverRPC/diverRPC.py", line 651, in route_new_variableset
    return flask.jsonify(diverAPI.new_variableset(user, projectid, name, desc,
  File "/home/jvc/diverRPC/diverAPI.py", line 639, in new_variableset
    procresult = proccall_errcheck(cursor, "API_CreateVariableSet",
  File "/home/jvc/diverRPC/diverAPI.py", line 139, in proccall_errcheck
    cursor.callproc(proc, procargs)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/cursors.py", line 258, in callproc
    self._query(q)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/jvc/mambaforge/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'jvc-Hallucinations' for key 'owner'")
```

I suspect this is also going to come up with cohorts and custom variables. Indeed, this may be part of what's causing #152.

**Comment by Viqsi** [comment]
Here is the current CREATE TABLE expression for diverVariableSets:
```
CREATE TABLE `diverVariableSets` (
  `variableSetId` int(11) NOT NULL AUTO_INCREMENT,
  `owner` varchar(32) DEFAULT NULL,
  `projectId` int(11) DEFAULT NULL,
  `name` varchar(64) DEFAULT NULL,
  `description` text DEFAULT NULL,
  PRIMARY KEY (`variableSetId`),
  UNIQUE KEY `owner` (`owner`,`name`)
) ENGINE=InnoDB AUTO_INCREMENT=85 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

The UNIQUE KEY does not include projectId. That's the source of the problem. I contend that a user would reasonably expect that if the current project doesn't have a variable set named "Shiny Things", that they can therefore create a variable set called "Shiny Things" in the current project without running into DIVER telling them "nope, you used that name in some other project you can't remember, you fail".

This consideration has already been done​ for cohorts (UNIQUE KEY `owner` (`owner`,`projectId`,`name`)), so there is precedent.
